from pilotscope.Anchor.BaseAnchor.BasePushHandler import CardPushHandler
from pilotscope.Factory.DBControllerFectory import DBControllerFactory
from pilotscope.PilotConfig import PilotConfig
from pilotscope.DBInteractor.PilotDataInteractor import PilotDataInteractor
from pilotscope.PilotModel import PilotModel
from pilotscope.PilotTransData import PilotTransData


class MscnCardPushHandler(CardPushHandler):

    def __init__(self, model: PilotModel, config: PilotConfig) -> None:
        super().__init__(config)
        self.mscn_model = model
        self.config = config
        self.data_interactor = PilotDataInteractor(config)

    def acquire_injected_data(self, sql):
        self.data_interactor.pull_subquery_card()
        data: PilotTransData = self.data_interactor.execute(sql)
        assert data.subquery_2_card is not None
        subquery_2_card = data.subquery_2_card

        # Filter out malformed subqueries generated by PostgreSQL Anchor's CTE handling bug
        # Bug: When processing nested CTEs (e.g., "scored AS ... FROM base"), PostgreSQL Anchor
        # sometimes generates invalid subqueries like "/* () */ SELECT COUNT(*) FROM ;"
        import re
        valid_subqueries = []
        invalid_subqueries = []

        for sq in subquery_2_card.keys():
            # Skip empty FROM clause (e.g., "SELECT COUNT(*) FROM ;")
            if re.search(r'FROM\s*[;)]', sq):
                invalid_subqueries.append(sq)
                continue
            # Skip correlated subquery placeholders (e.g., "/* sdi.ticker */")
            if re.search(r'/\*\s*\w+\.\w+\s*\*/', sq):
                invalid_subqueries.append(sq)
                continue
            valid_subqueries.append(sq)

        # If no valid subqueries, fall back to PostgreSQL estimates for all
        if not valid_subqueries:
            print(f"⚠️  No valid subqueries found ({len(invalid_subqueries)} malformed), using PostgreSQL fallback")
            return subquery_2_card

        try:
            # Predict cardinalities for VALID subqueries only
            _, preds_unnorm, t_total = self.mscn_model.model.predict(valid_subqueries)
            # Mscn can only handler card that is larger than 0, so we add 1 to all
            # cards in training. In prediction we minus it by 1.
            new_subquery_2_card = {sq: str(max(0.0, pred - 1)) for sq, pred in zip(valid_subqueries, preds_unnorm)}

            # For invalid subqueries, use PostgreSQL's estimates (already in subquery_2_card)
            for sq in invalid_subqueries:
                new_subquery_2_card[sq] = subquery_2_card[sq]

            if invalid_subqueries:
                print(f"MSCN estimates OK ({len(valid_subqueries)} valid, {len(invalid_subqueries)} skipped)")
            else:
                print("MSCN estimates OK")
        except ValueError as e:
            # ValueError from parsing errors should be raised
            # These indicate the query is fundamentally incompatible
            error_str = str(e).lower()
            if "cte" in error_str or "parsing failed" in error_str:
                print(f"❌ MSCN prediction failed (query incompatible): {str(e)[:150]}")
                raise  # Re-raise to fail the query
            else:
                # Other ValueErrors might be recoverable, fall back to PostgreSQL estimates
                print(f"⚠️  MSCN prediction error (using PostgreSQL fallback): {str(e)[:150]}")
                new_subquery_2_card = subquery_2_card
        except Exception as e:
            # Check if this is a parsing error (sqlglot.errors.ParseError or similar)
            error_str = str(e).lower()
            if any(keyword in error_str for keyword in ["expected table", "parse", "parsing", "cte", "syntax error"]):
                print(f"❌ MSCN prediction failed (parsing error): {str(e)[:150]}")
                raise  # Re-raise to fail the query
            else:
                # For other exceptions, fall back to PostgreSQL estimates
                print(f"⚠️  MSCN prediction error (using PostgreSQL fallback): {str(e)[:150]}")
                new_subquery_2_card = subquery_2_card
        return new_subquery_2_card
