from sqlglot import parse_one, exp
from algorithm_examples.Lero.source.utils import PlanCardReplacer
from algorithm_examples.Lero.source.card_picker import CardPicker
import re

class CardsPickerModel():
    def __init__(self, subqueries, rows) -> None:
        """
        subqueries: iterable of subquery SQL strings (from Anchor)
        rows: iterable of cardinality values aligned with subqueries
        """
        self.swing_factor_lower_bound = 0.1**2
        self.swing_factor_upper_bound = 10**2
        self.swing_factor_step = 10

        # Filter out malformed subqueries generated by PostgreSQL Anchor (CTE bug)
        # - Empty FROM: "SELECT COUNT(*) FROM ;"
        # - Correlated placeholder: "/* sdi.ticker */"
        invalid_patterns = [
            re.compile(r"FROM\s*[;)]", re.IGNORECASE),
            re.compile(r"/\*\s*\w+\.\w+\s*\*/")
        ]

        filtered_subqueries = []
        filtered_rows = []
        skipped_empty_from = 0
        skipped_placeholder = 0

        for sq, row in zip(list(subqueries), list(rows)):
            if any(p.search(sq) for p in invalid_patterns):
                if "/*" in sq:
                    skipped_placeholder += 1
                else:
                    skipped_empty_from += 1
                continue
            try:
                # Validate parse to avoid downstream crashes
                qmd = QueryMetaData(sq)
                filtered_subqueries.append(qmd)
                filtered_rows.append(row)
            except Exception:
                skipped_empty_from += 1
                continue

        if skipped_empty_from or skipped_placeholder:
            print(f"Lero: filtered malformed subqueries (empty_from={skipped_empty_from}, placeholder={skipped_placeholder})")

        self.tables = [q.tables for q in filtered_subqueries]
        self.rows = filtered_rows

        # If nothing valid remains, avoid failures by setting empty lists
        if not self.tables:
            self.isMultiTables = []
            self.join_rel_tables = []
            self.join_rel_rows = []
            self.base_rel_rows = []
            self.card_picker = None
            self.plan_card_replacer = PlanCardReplacer([], [])
            return

        self.isMultiTables = [len(table) > 1 for table in self.tables]  # [F, ..., T]
        self.join_rel_tables = [x for x, b in zip(self.tables, self.isMultiTables) if b]
        self.join_rel_rows = [x for x, b in zip(self.rows, self.isMultiTables) if b]
        self.base_rel_rows = [x for x, b in zip(self.rows, self.isMultiTables) if not b]
        if len(self.join_rel_rows) > 0:
            self.card_picker = CardPicker(
                self.join_rel_rows,
                self.join_rel_tables,
                self.swing_factor_lower_bound,
                self.swing_factor_upper_bound,
                self.swing_factor_step
            )
        else:
            self.card_picker = None
        self.plan_card_replacer = PlanCardReplacer(self.join_rel_tables, self.join_rel_rows)

    def get_cards(self):
        if self.card_picker:
            finish = self.card_picker.next()
            new_cards = self.base_rel_rows + self.card_picker.get_card_list()
            return finish, new_cards
        else:
            # No join_rel_rows, we do not need card_picker
            return True, self.base_rel_rows
        
    
    # Lero guides the optimizer to generate different plans by changing cardinalities,
    # but row count will be used as the input feature when predicting the plan score.
    # So we need to restore all the row counts to the original values before feeding the model.
    def replace(self, plan):
        if "Plan" in plan:
            plan = plan["Plan"]
        self.plan_card_replacer.replace(plan)

class QueryMetaData():
    def __init__(self, queryString, replace_alias=True) -> None:
        self.raw = queryString
        self.expression = parse_one(self.raw)
        self.tables = []
        self.table_alias = []
        self.names_to_alias = {}
        self.alias_to_names = {}
        self._parse_table()
        self.replace_alias = replace_alias
        self.sql_without_alias = self.raw
        self.expression_origin = self.expression
        if self.replace_alias:
            self._replace_table_alias()
        self.conditions = [] # Element Type: sqlglot.expressions.EQ. If need str type, use sql() method 
        self.joins = []      # Element Type: sqlglot.expressions.EQ. If need str type, use sql() method 
        self._parse_predicates()
        
    def _parse_table(self):
        # CTE support: collect real tables inside CTEs, skip CTE aliases
        cte_aliases = set()

        for cte in self.expression.find_all(exp.CTE, bfs=False):
            cte_alias = cte.alias
            if cte_alias:
                cte_aliases.add(cte_alias)

            cte_query = cte.this
            if cte_query:
                for table in cte_query.find_all(exp.Table, bfs=False):
                    if table.name not in self.tables and table.name not in cte_aliases:
                        self.tables.append(table.name)

        for table in self.expression.find_all(exp.Table, bfs=False):
            if table.name in cte_aliases:
                continue

            if table.name not in self.tables:
                self.tables.append(table.name)
            if table.alias:
                self.table_alias.append(table.alias)
                self.names_to_alias[table.name] = table.alias
                self.alias_to_names[table.alias] = table.name

        if not self.tables:
            raise ValueError(
                f"Lero QueryMetaData parsing failed: no tables found in query: {self.raw[:200]}"
            )
                
    def _replace_table_alias(self):
        for k, v in self.alias_to_names.items():
            # print(k, v)
            self.sql_without_alias = self.sql_without_alias.replace(k+'.', v+'.')
        self.expression = parse_one(self.sql_without_alias)
        while self.expression.find(exp.TableAlias):
            self.expression.find(exp.TableAlias).pop()
        # print(self.expression)
    
    def _parse_predicates(self):
        # First, extract JOIN ON predicates from JOIN nodes
        join_on_predicates = set()
        for join_node in self.expression.find_all(exp.Join):
            on_clause = join_node.args.get('on')
            if on_clause:
                # The ON clause can be a single predicate or multiple predicates connected by AND
                self._extract_join_predicates(on_clause, join_on_predicates)

        # Now process all predicates from the main query (not subqueries)
        # We only want to process predicates that are direct children of the main SELECT
        for pre in self.expression.find_all(exp.Predicate, bfs=False):
            # Check if this predicate is part of JOIN ON clause
            if id(pre) in join_on_predicates:
                # This is a JOIN ON predicate
                columns = list(pre.find_all(exp.Column, bfs=False))
                if len(columns) == 2:
                    self.joins.append(pre)
            else:
                # This is a WHERE clause predicate (or from subquery)
                # For Lero, we only handle single-column predicates in conditions
                # Multi-column predicates in WHERE (like correlated subqueries) are skipped
                columns = list(pre.find_all(exp.Column, bfs=False))
                if len(columns) == 1:
                    self.conditions.append(pre)
                # Note: We don't add 2-column WHERE predicates to joins
                # This handles correlated subqueries correctly

    def _extract_join_predicates(self, node, predicate_set):
        """Recursively extract all predicates from a JOIN ON clause"""
        if isinstance(node, exp.Predicate):
            predicate_set.add(id(node))
        elif isinstance(node, (exp.And, exp.Or)):
            # Recursively process AND/OR nodes
            for child in [node.left, node.right]:
                if child:
                    self._extract_join_predicates(child, predicate_set)
            
    def __str__(self):
        return '\n'.join(["{}: {}".format(k, "[{}]".format(', '.join([s.sql() for s in v])) if (isinstance(v, list) and len(v) != 0 and hasattr(v[0], 'sql')) else v) for k, v in self.__dict__.items()])
